on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Run install
        run: pnpm install
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci src/

  # sonarqube:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up pnpm
  #       uses: pnpm/action-setup@v2

  #     - name: Install dependencies
  #       run: pnpm install
        
  #     - name: SonarQube Scan
  #       uses: SonarSource/sonarcloud-github-action@v1.4
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
